// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/feiquan123/go-program-framework/src/app/ops"
	"github.com/feiquan123/go-program-framework/src/pkg/app"
	"github.com/feiquan123/go-program-framework/src/pkg/config"
	"github.com/feiquan123/go-program-framework/src/pkg/log"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewAPP(config2 string) (*app.Application, error) {
	viper, err := config.New(config2)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.New(options)
	if err != nil {
		return nil, err
	}
	application, err := ops.NewAPP(viper, logger)
	if err != nil {
		return nil, err
	}
	return application, nil
}

// wire.go:

var providerSet = wire.NewSet(log.ProviderSet, config.ProviderSet, ops.ProviderSet)
